<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.3.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\EmptyEngine.Core\EmptyEngine.Core.csproj" />
    <ProjectReference Include="..\..\Core\EmptyEngine.Editor\EmptyEngine.Editor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EmptyEngine.SceneSource.Tests" />
    <InternalsVisibleTo Include="EmptyEngine.World.Tests" />
  </ItemGroup>

</Project>
