<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>0.3.3</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Shims\IsExternalInit.cs" Link="Shims\IsExternalInit.cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EmptyEngine.Tests" />
  </ItemGroup>

</Project>
