<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\EmptyEngine.Core\EmptyEngine.Core.csproj" />
    <ProjectReference Include="..\..\Core\EmptyEngine.Editor\EmptyEngine.Editor.csproj" />
    <ProjectReference Include="..\EmptyEngine.Serialization\EmptyEngine.Serialization.csproj" />
    <ProjectReference Include="..\EmptyEngine.Storage.Editor\EmptyEngine.Storage.Editor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EmptyEngine.Serialization.Tests" />
  </ItemGroup>

</Project>
