<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>0.5.2</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Shims\IsExternalInit.cs" Link="Shims\IsExternalInit.cs" />
    <Compile Include="..\..\Shims\ReferenceEqualityComparer.cs" Link="Shims\ReferenceEqualityComparer.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\EmptyEngine.Core\EmptyEngine.Core.csproj" />
    <ProjectReference Include="..\EmptyEngine.ObjectModel\EmptyEngine.ObjectModel.csproj" />
  </ItemGroup>

</Project>
