using System.Text;
using Microsoft.CodeAnalysis;

namespace EmptyEngine.Serialization.Generator;

/// <summary><see cref="TypePlan"/> / <see cref="ValuePlan"/> の C# への出力</summary>
internal sealed class SerializerEmitter
{
    private const string Reader = "global::MessagePack.MessagePackReader";
    private const string Writer = "global::MessagePack.MessagePackWriter";
    private const string Options = "global::MessagePack.MessagePackSerializerOptions";
    private const string Serializer = "global::EmptyEngine.Serialization.ITypeSerializer";
    private const string Table = "global::System.Collections.Generic.Dictionary<string, " + Serializer + ">";
    private const string ReadOnlyTable = "global::System.Collections.Generic.IReadOnlyDictionary<string, " + Serializer + ">";
    private const string Binary = "global::EmptyEngine.Core.IAssetBinary";
    private const string Uninitialized = "global::System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject";
    private const string Unbox = "global::System.Runtime.CompilerServices.Unsafe.Unbox";

    private readonly StringBuilder _sb = new();
    private int _indent;

    public string Emit(IReadOnlyList<TypePlan> types, IEnumerable<ValuePlan> plans)
    {
        Line("// <auto-generated />");
        Line("#nullable disable");
        Line("#pragma warning disable CS8600, CS8601, CS8603, CS8604, CS8625");
        Line();
        Line("namespace EmptyEngine.Serialization.Generated");
        Open();

        EmitRegistry(types);

        foreach (ValuePlan plan in plans.Where(p => p.CodecName.Length > 0)
                     .OrderBy(p => p.CodecName, System.StringComparer.Ordinal))
        {
            Line();
            EmitCodec(plan);
        }

        foreach (TypePlan type in types)
        {
            Line();
            EmitSerializer(type);
        }

        Close();
        return _sb.ToString();
    }

    private void EmitRegistry(IReadOnlyList<TypePlan> types)
    {
        Line("/// <summary>型ごとのシリアライズと復元</summary>");
        Line("internal static class GeneratedSerializers");
        Open();
        Line("/// <summary>ワイヤ上の型名に対応するシリアライザ</summary>");
        Line($"internal static readonly {ReadOnlyTable} ByName = new {Table}({types.Count}, global::System.StringComparer.Ordinal)");
        Line("{");
        _indent++;
        foreach (TypePlan type in types)
            Line($"{{ \"{type.WireName}\", {type.SerializerName}.Instance }},");
        _indent--;
        Line("};");
        Line();
        Line("/// <summary>型ごとのシリアライザを登録する</summary>");
        Line("[global::System.Runtime.CompilerServices.ModuleInitializer]");
        Line("internal static void Install() => global::EmptyEngine.Serialization.TypeSerializers.Install(ByName);");
        Close();
    }

    private void EmitCodec(ValuePlan plan)
    {
        Line($"internal static class {plan.CodecName}");
        Open();

        switch (plan.Kind)
        {
            case ValueKind.Contract:
                EmitContractCodec(plan);
                break;
            case ValueKind.Array:
                EmitArrayCodec(plan);
                break;
            case ValueKind.List:
                EmitListCodec(plan);
                break;
            case ValueKind.Nullable:
                EmitNullableCodec(plan);
                break;
            case ValueKind.Reference:
                EmitReferenceCodec(plan);
                break;
        }

        Close();
    }

    private void EmitContractCodec(ValuePlan plan)
    {
        string type = plan.TypeExpression;
        bool isClass = !plan.IsValueType;

        Line($"public static void Write(ref {Writer} writer, {type} value, {Options} options)");
        Open();
        if (isClass)
        {
            Line("if (value == null) { writer.WriteNil(); return; }");
        }

        Line($"writer.WriteMapHeader({plan.Members.Count});");
        foreach (ContractMember member in plan.Members)
        {
            Line($"writer.Write(\"{member.Key}\");");
            WriteValue(member.Value, $"value.{member.Name}");
        }

        Close();

        Line();
        Line($"public static {type} Read(ref {Reader} reader, {Options} options)");
        Open();
        if (isClass)
            Line("if (reader.TryReadNil()) { return null; }");
        Line($"{type} value = {NewUninitialized(plan)};");
        Line("ReadInto(ref reader, ref value, options);");
        Line("return value;");
        Close();

        Line();
        Line("/// <summary>既にある実体への読み込み</summary>");
        Line($"public static void ReadInto(ref {Reader} reader, ref {type} value, {Options} options)");
        Open();
        Line("if (reader.TryReadNil()) { return; }");
        Line("int count = reader.ReadMapHeader();");
        Line("for (int i = 0; i < count; i++)");
        Open();
        Line("switch (reader.ReadString())");
        Open();
        foreach (ContractMember member in plan.Members)
        {
            Line($"case \"{member.Key}\":");
            _indent++;
            Line($"value.{member.Name} = {ReadValue(member.Value)};");
            Line("break;");
            _indent--;
        }

        Line("default:");
        _indent++;
        Line("reader.Skip();");
        Line("break;");
        _indent--;
        Close();
        Close();
        Close();

        Line();
        Line($"public static void CopyShallow(ref {type} destination, in {type} source)");
        Open();
        foreach (ContractMember member in plan.Members)
            Line($"destination.{member.Name} = source.{member.Name};");
        Close();

        Line();
        Line($"public static void CopyDeep(ref {type} destination, in {type} source)");
        Open();
        foreach (ContractMember member in plan.Members)
            Line($"destination.{member.Name} = {CloneValue(member.Value, $"source.{member.Name}")};");
        Close();

        Line();
        Line($"public static {type} Clone({type} value)");
        Open();
        if (isClass)
            Line("if (value == null) { return null; }");
        Line($"{type} copy = {NewUninitialized(plan)};");
        Line("CopyDeep(ref copy, in value);");
        Line("return copy;");
        Close();
    }

    private void EmitArrayCodec(ValuePlan plan)
    {
        ValuePlan element = plan.Element!;
        string type = plan.TypeExpression;
        string elementType = element.TypeExpression;

        Line($"public static void Write(ref {Writer} writer, {type} value, {Options} options)");
        Open();
        Line("if (value == null) { writer.WriteNil(); return; }");
        Line("writer.WriteArrayHeader(value.Length);");
        Line("for (int i = 0; i < value.Length; i++)");
        Open();
        WriteValue(element, "value[i]");
        Close();
        Close();

        Line();
        Line($"public static {type} Read(ref {Reader} reader, {Options} options)");
        Open();
        Line("if (reader.TryReadNil()) { return null; }");
        Line("int count = reader.ReadArrayHeader();");
        Line($"var value = new {elementType}[count];");
        Line("for (int i = 0; i < count; i++)");
        Open();
        Line($"value[i] = {ReadValue(element)};");
        Close();
        Line("return value;");
        Close();

        Line();
        Line($"public static {type} Clone({type} value)");
        Open();
        Line("if (value == null) { return null; }");
        if (element.CopiedByValue)
        {
            Line($"return ({type})value.Clone();");
        }
        else
        {
            Line($"var copy = new {elementType}[value.Length];");
            Line("for (int i = 0; i < value.Length; i++)");
            Open();
            Line($"copy[i] = {CloneValue(element, "value[i]")};");
            Close();
            Line("return copy;");
        }

        Close();
    }

    private void EmitListCodec(ValuePlan plan)
    {
        ValuePlan element = plan.Element!;
        string type = plan.TypeExpression;

        Line($"public static void Write(ref {Writer} writer, {type} value, {Options} options)");
        Open();
        Line("if (value == null) { writer.WriteNil(); return; }");
        Line("writer.WriteArrayHeader(value.Count);");
        Line("for (int i = 0; i < value.Count; i++)");
        Open();
        WriteValue(element, "value[i]");
        Close();
        Close();

        Line();
        Line($"public static {type} Read(ref {Reader} reader, {Options} options)");
        Open();
        Line("if (reader.TryReadNil()) { return null; }");
        Line("int count = reader.ReadArrayHeader();");
        Line($"var value = new {type}(count);");
        Line("for (int i = 0; i < count; i++)");
        Open();
        Line($"value.Add({ReadValue(element)});");
        Close();
        Line("return value;");
        Close();

        Line();
        Line($"public static {type} Clone({type} value)");
        Open();
        Line("if (value == null) { return null; }");
        if (element.CopiedByValue)
        {
            Line($"return new {type}(value);");
        }
        else
        {
            Line($"var copy = new {type}(value.Count);");
            Line("for (int i = 0; i < value.Count; i++)");
            Open();
            Line($"copy.Add({CloneValue(element, "value[i]")});");
            Close();
            Line("return copy;");
        }

        Close();
    }

    private void EmitNullableCodec(ValuePlan plan)
    {
        ValuePlan element = plan.Element!;
        string type = plan.TypeExpression;

        Line($"public static void Write(ref {Writer} writer, {type} value, {Options} options)");
        Open();
        Line("if (!value.HasValue) { writer.WriteNil(); return; }");
        WriteValue(element, "value.Value");
        Close();

        Line();
        Line($"public static {type} Read(ref {Reader} reader, {Options} options)");
        Open();
        Line("if (reader.TryReadNil()) { return null; }");
        Line($"return {ReadValue(element)};");
        Close();

        Line();
        Line($"public static {type} Clone({type} value)");
        Open();
        Line("if (!value.HasValue) { return null; }");
        Line($"return {CloneValue(element, "value.Value")};");
        Close();
    }

    /// <summary>参照 1 個＝キーの文字列。実体は単一メンバの struct なので、そこへ書き戻すだけ</summary>
    private void EmitReferenceCodec(ValuePlan plan)
    {
        string type = plan.TypeExpression;

        Line($"public static void Write(ref {Writer} writer, {type} value, {Options} options)");
        Line($"    => writer.Write(value.{plan.ReferenceMember});");

        Line();
        Line($"public static {type} Read(ref {Reader} reader, {Options} options)");
        Open();
        Line($"{type} value = default;");
        Line($"value.{plan.ReferenceMember} = reader.ReadString();");
        Line("return value;");
        Close();

        Line();
        Line($"public static {type} Clone({type} value) => value;");
    }

    private void EmitSerializer(TypePlan type)
    {
        ValuePlan plan = type.Value;
        string clr = type.TypeExpression;

        Line($"internal sealed class {type.SerializerName} : {Serializer}");
        Open();
        Line($"internal static readonly {type.SerializerName} Instance = new {type.SerializerName}();");
        Line();
        Line($"public global::System.Type Type => typeof({clr});");
        Line();
        Line($"public string TypeName => \"{type.WireName}\";");
        Line();
        Line(plan.IsValueType
            ? $"public object CreateUninitialized() => (object)default({clr});"
            : $"public object CreateUninitialized() => {NewUninitialized(plan)};");
        Line();

        Line($"public void Read(ref {Reader} reader, object instance, {Options} options)");
        Open();
        Line("if (reader.TryReadNil()) { return; }");
        if (plan.IsValueType)
        {
            Line($"{plan.CodecName}.ReadInto(ref reader, ref {Unbox}<{clr}>(instance), options);");
        }
        else
        {
            Line($"var target = ({clr})instance;");
            Line($"{plan.CodecName}.ReadInto(ref reader, ref target, options);");
        }

        Close();
        Line();

        Line($"public void Write(ref {Writer} writer, object instance, {Options} options)");
        Line($"    => {plan.CodecName}.Write(ref writer, ({clr})instance, options);");
        Line();

        EmitConstruct(type);
        Line();

        EmitCopy(type, deep: false);
        Line();
        EmitCopy(type, deep: true);

        if (type.Binaries.Count > 0)
            EmitBinaries(type);

        Close();
    }

    private void EmitConstruct(TypePlan type)
    {
        Line("public object Construct(global::System.IServiceProvider services)");
        Open();

        foreach (ConstructorPlan constructor in type.Constructors)
        {
            if (constructor.Parameters.Count == 0)
            {
                Line($"return new {type.TypeExpression}();");
                Close();
                return;
            }

            Open();
            var arguments = new List<string>();
            var gates = new List<string>();
            for (int i = 0; i < constructor.Parameters.Count; i++)
            {
                ParameterPlan parameter = constructor.Parameters[i];
                if (parameter.IsValueType)
                {
                    arguments.Add(parameter.DefaultLiteral!);
                    continue;
                }

                string local = $"argument{i}";
                Line($"var {local} = services.GetService(typeof({parameter.TypeExpression})) as {parameter.TypeExpression};");
                if (parameter.DefaultLiteral is null)
                    gates.Add($"{local} != null");
                arguments.Add(parameter.DefaultLiteral is null ? local : $"{local} ?? {parameter.DefaultLiteral}");
            }

            string condition = gates.Count > 0 ? string.Join(" && ", gates) : "true";
            Line($"if ({condition}) {{ return new {type.TypeExpression}({string.Join(", ", arguments)}); }}");
            Close();
        }

        Line("throw new global::System.InvalidOperationException(");
        Line($"    \"Cannot construct '{type.WireName}': no constructor had all of its arguments available from the \" +");
        Line("    \"service provider. Declare a parameterless constructor if it needs no injection.\");");
        Close();
    }

    private void EmitCopy(TypePlan type, bool deep)
    {
        string name = deep ? "CopyDeep" : "CopyShallow";
        string clr = type.TypeExpression;

        Line($"public void {name}(object destination, object source)");
        Open();
        if (type.Value.IsValueType)
        {
            Line($"{type.Value.CodecName}.{name}(ref {Unbox}<{clr}>(destination), in {Unbox}<{clr}>(source));");
        }
        else
        {
            Line($"var target = ({clr})destination;");
            Line($"var origin = ({clr})source;");
            Line($"{type.Value.CodecName}.{name}(ref target, in origin);");
        }

        Close();
    }

    private void EmitBinaries(TypePlan type)
    {
        Line();
        Line($"public int BinaryCount => {type.Binaries.Count};");
        Line();
        Line($"public {Binary} GetBinary(object instance, int index)");
        Open();
        Line($"var target = ({type.TypeExpression})instance;");
        Line("switch (index)");
        Open();
        for (int i = 0; i < type.Binaries.Count; i++)
            Line($"case {i}: return target.{type.Binaries[i].Name};");
        Line("default: throw new global::System.ArgumentOutOfRangeException(nameof(index));");
        Close();
        Close();
        Line();
        Line($"public void SetBinary(object instance, int index, {Binary} value)");
        Open();
        Line($"var target = ({type.TypeExpression})instance;");
        Line("switch (index)");
        Open();
        for (int i = 0; i < type.Binaries.Count; i++)
        {
            Line($"case {i}:");
            _indent++;
            Line($"target.{type.Binaries[i].Name} = ({ModelBuilder.Expression(type.Binaries[i].Type)})value;");
            Line("break;");
            _indent--;
        }

        Line("default: throw new global::System.ArgumentOutOfRangeException(nameof(index));");
        Close();
        Close();
    }

    private void WriteValue(ValuePlan plan, string value)
    {
        switch (plan.Kind)
        {
            case ValueKind.Primitive:
            case ValueKind.String:
                Line($"writer.Write({value});");
                break;
            case ValueKind.Enum:
                Line($"writer.Write(({UnderlyingOf(plan)}){value});");
                break;
            default:
                Line($"{plan.CodecName}.Write(ref writer, {value}, options);");
                break;
        }
    }

    private string ReadValue(ValuePlan plan) => plan.Kind switch
    {
        ValueKind.Primitive => $"reader.{plan.ReaderMethod}()",
        ValueKind.String => "reader.ReadString()",
        ValueKind.Enum => $"({plan.TypeExpression})reader.{plan.ReaderMethod}()",
        _ => $"{plan.CodecName}.Read(ref reader, options)",
    };

    private string CloneValue(ValuePlan plan, string value)
    {
        if (plan.CopiedByValue)
            return value;

        if (plan.Kind == ValueKind.Array && plan.Element!.CopiedByValue)
            return $"({value} == null ? null : ({plan.TypeExpression}){value}.Clone())";

        return $"{plan.CodecName}.Clone({value})";
    }

    private static string UnderlyingOf(ValuePlan plan)
        => ModelBuilder.Expression(((INamedTypeSymbol)plan.Type).EnumUnderlyingType!);

    private static string NewUninitialized(ValuePlan plan)
        => plan.IsValueType
            ? "default"
            : $"({plan.TypeExpression}){Uninitialized}(typeof({plan.TypeExpression}))";

    private void Line(string text = "")
    {
        if (text.Length > 0)
            _sb.Append(' ', _indent * 4).AppendLine(text);
        else
            _sb.AppendLine();
    }

    private void Open()
    {
        Line("{");
        _indent++;
    }

    private void Close()
    {
        _indent--;
        Line("}");
    }
}
