using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EmptyEngine.Generators;

/// <summary><c>[ResolveAsset]</c> 付きフィールドからの参照プロパティと解決コードの生成</summary>
[Generator(LanguageNames.CSharp)]
public sealed class ResolveAssetGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "EmptyEngine.Generators.ResolveAssetAttribute";

    private const string HookMethodName = "OnResolveAssetsAsync";

    private const string AttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace EmptyEngine.Generators
        {
            /// <summary>解決済みアセット実体を受け取る private フィールドに付ける属性</summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Field)]
            internal sealed class ResolveAssetAttribute : global::System.Attribute
            {
                public ResolveAssetAttribute()
                {
                }

                public ResolveAssetAttribute(string referenceName)
                {
                    ReferenceName = referenceName;
                }

                /// <summary>生成する参照プロパティ名</summary>
                public string? ReferenceName { get; }
            }
        }
        """;

    private static readonly DiagnosticDescriptor NotPartial = new(
        "EEGEN001", "Type must be partial",
        "Type '{0}' (and its containing types) must be declared partial to use [ResolveAsset]",
        "EmptyEngine.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NotClass = new(
        "EEGEN002", "Only classes are supported",
        "[ResolveAsset] can only be used on fields of a reference type (class). '{0}' is not a class.",
        "EmptyEngine.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidField = new(
        "EEGEN003", "Unsupported field",
        "[ResolveAsset] field '{0}' must be non-static, non-public, and of a reference type (class/interface)",
        "EmptyEngine.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NameCollision = new(
        "EEGEN004", "Property name collision",
        "Generated property name '{0}' collides with an existing member. Specify another name with [ResolveAsset(\"OtherName\")].",
        "EmptyEngine.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor BaseHookNotOverridable = new(
        "EEGEN007", "Base OnResolveAssetsAsync cannot be overridden",
        "The base type of '{0}' does not declare OnResolveAssetsAsync as virtual/override, so the one generated for [ResolveAsset] cannot replace it. Declare OnResolveAssetsAsync in '{0}' and call ResolveAssetFieldsAsync from it.",
        "EmptyEngine.Generators", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ResolveAssetAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValueProvider<ImmutableArray<FieldModel>> fields = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is VariableDeclaratorSyntax,
                transform: static (ctx, _) => CreateModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!)
            .Collect();

        context.RegisterSourceOutput(fields, static (spc, all) => Emit(spc, all));
    }

    /// <summary>1 属性適用 1 モデル</summary>
    private sealed class FieldModel
    {
        public string Namespace = string.Empty;
        /// <summary>外側 → 対象型の順の入れ子宣言</summary>
        public string[] TypeChain = [];
        public string TypeKey = string.Empty;
        public bool IsPartialChain;
        public bool IsClass;
        public bool HasOnCreated;
        public bool HasOnDestroy;
        public bool HasOnDeserialized;
        public bool HasOnResolveAssets;
        /// <summary>基底クラス連鎖のライフサイクルメソッド宣言状況</summary>
        public BaseMethod BaseOnCreated;
        public BaseMethod BaseOnDestroy;
        public BaseMethod BaseOnDeserialized;
        public BaseMethod BaseOnResolveAssets;
        /// <summary>基底が既に ILifecycleAttachable を実装しているか</summary>
        public bool BaseHasLifecycleInterface;
        /// <summary>基底が既に IAssetResolutionHook を実装しているか</summary>
        public bool BaseHasHookInterface;
        public string[] MemberNames = [];
        public string FieldName = string.Empty;
        public string PropertyName = string.Empty;
        public string FieldTypeFqn = string.Empty;
        public bool IsFieldValid;
        public Location? Location;
    }

    private static FieldModel? CreateModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not IFieldSymbol field)
            return null;
        if (field.Type is IErrorTypeSymbol)
            return null;

        INamedTypeSymbol type = field.ContainingType;

        var chain = new List<string>();
        bool partialChain = true;
        for (INamedTypeSymbol? t = type; t is not null; t = t.ContainingType)
        {
            chain.Insert(0, $"{TypeKeyword(t)} {NameWithTypeParameters(t)}");
            partialChain &= IsDeclaredPartial(t);
        }

        string? explicitName = ctx.Attributes.Length > 0
                               && ctx.Attributes[0].ConstructorArguments.Length > 0
                               && ctx.Attributes[0].ConstructorArguments[0].Value is string s
                               && !string.IsNullOrWhiteSpace(s)
            ? s
            : null;

        return new FieldModel
        {
            Namespace = type.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : type.ContainingNamespace.ToDisplayString(),
            TypeChain = chain.ToArray(),
            TypeKey = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsPartialChain = partialChain,
            IsClass = type.TypeKind == TypeKind.Class,
            HasOnCreated = HasMethod(type, "OnCreated"),
            HasOnDestroy = HasMethod(type, "OnDestroy"),
            HasOnDeserialized = HasMethod(type, "OnDeserialized"),
            HasOnResolveAssets = HasMethod(type, HookMethodName),
            BaseOnCreated = FindBaseMethod(type, "OnCreated"),
            BaseOnDestroy = FindBaseMethod(type, "OnDestroy"),
            BaseOnDeserialized = FindBaseMethod(type, "OnDeserialized"),
            BaseOnResolveAssets = FindBaseMethod(type, HookMethodName),
            BaseHasLifecycleInterface = type.BaseType?.AllInterfaces.Any(i =>
                i.ToDisplayString() == "EmptyEngine.ObjectModel.ILifecycleAttachable") ?? false,
            BaseHasHookInterface = type.BaseType?.AllInterfaces.Any(i =>
                i.ToDisplayString() == "EmptyEngine.Core.IAssetResolutionHook") ?? false,
            MemberNames = type.MemberNames.ToArray(),
            FieldName = field.Name,
            PropertyName = explicitName ?? DerivePropertyName(field.Name),
            FieldTypeFqn = field.Type
                .WithNullableAnnotation(NullableAnnotation.NotAnnotated)
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsFieldValid = !field.IsStatic && !field.IsConst
                           && field.DeclaredAccessibility != Accessibility.Public
                           && field.Type.IsReferenceType,
            Location = ctx.TargetNode.GetLocation(),
        };
    }

    private static bool IsDeclaredPartial(INamedTypeSymbol type)
        => type.DeclaringSyntaxReferences.Any(r =>
            r.GetSyntax() is TypeDeclarationSyntax decl && decl.Modifiers.Any(SyntaxKind.PartialKeyword));

    private static bool HasMethod(INamedTypeSymbol type, string name)
        => type.GetMembers().OfType<IMethodSymbol>().Any(m =>
            m.MethodKind is MethodKind.Ordinary or MethodKind.ExplicitInterfaceImplementation
            && (m.Name == name || m.Name.EndsWith("." + name, StringComparison.Ordinal)));

    /// <summary>基底連鎖でのライフサイクルメソッドの宣言状況</summary>
    internal enum BaseMethod
    {
        /// <summary>基底クラスに対象のメソッドがない</summary>
        None,
        /// <summary>virtual/override があり本体も持つ宣言</summary>
        Overridable,
        /// <summary>最寄りの宣言が abstract</summary>
        OverridableAbstract,
        /// <summary>非 virtual または sealed＝置き換え不能</summary>
        NotOverridable,
    }

    private static BaseMethod FindBaseMethod(INamedTypeSymbol type, string name)
    {
        for (INamedTypeSymbol? t = type.BaseType; t is not null; t = t.BaseType)
        {
            IMethodSymbol? method = t.GetMembers(name).OfType<IMethodSymbol>()
                .FirstOrDefault(m => m.MethodKind == MethodKind.Ordinary);
            if (method is null)
                continue;
            if (method.IsSealed || !(method.IsVirtual || method.IsAbstract || method.IsOverride))
                return BaseMethod.NotOverridable;
            return method.IsAbstract ? BaseMethod.OverridableAbstract : BaseMethod.Overridable;
        }

        return BaseMethod.None;
    }

    private static string TypeKeyword(INamedTypeSymbol type)
        => type.IsRecord
            ? (type.TypeKind == TypeKind.Struct ? "record struct" : "record")
            : type.TypeKind switch
            {
                TypeKind.Struct => "struct",
                TypeKind.Interface => "interface",
                _ => "class",
            };

    private static string NameWithTypeParameters(INamedTypeSymbol type)
        => type.TypeParameters.Length == 0
            ? type.Name
            : $"{type.Name}<{string.Join(", ", type.TypeParameters.Select(p => p.Name))}>";

    /// <summary>フィールド名からの参照プロパティ名の導出</summary>
    private static string DerivePropertyName(string fieldName)
    {
        string s = fieldName;
        if (s.StartsWith("m_", StringComparison.Ordinal))
            s = s.Substring(2);
        s = s.TrimStart('_');
        if (s.Length == 0)
            s = fieldName;
        s = char.ToUpperInvariant(s[0]) + s.Substring(1);
        return s == fieldName ? s + "Reference" : s;
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<FieldModel> all)
    {
        foreach (IGrouping<string, FieldModel> group in all.GroupBy(f => f.TypeKey, StringComparer.Ordinal))
        {
            FieldModel first = group.First();
            string typeName = first.TypeChain[first.TypeChain.Length - 1];

            if (!first.IsClass)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NotClass, first.Location, typeName));
                continue;
            }

            if (!first.IsPartialChain)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NotPartial, first.Location, typeName));
                continue;
            }

            var usedNames = new HashSet<string>(first.MemberNames, StringComparer.Ordinal);
            var valid = new List<FieldModel>();
            foreach (FieldModel f in group)
            {
                if (!f.IsFieldValid)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(InvalidField, f.Location, f.FieldName));
                    continue;
                }

                if (!usedNames.Add(f.PropertyName))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(NameCollision, f.Location, f.PropertyName));
                    continue;
                }

                valid.Add(f);
            }

            if (valid.Count == 0)
                continue;

            if (!first.HasOnResolveAssets && first.BaseOnResolveAssets == BaseMethod.NotOverridable)
                spc.ReportDiagnostic(Diagnostic.Create(BaseHookNotOverridable, first.Location, typeName));

            spc.AddSource(HintName(first), SourceText.From(BuildSource(first, valid), Encoding.UTF8));
        }
    }

    private static string HintName(FieldModel model)
    {
        var sb = new StringBuilder();
        if (model.Namespace.Length > 0)
            sb.Append(model.Namespace).Append('.');
        sb.Append(string.Join(".", model.TypeChain.Select(c => c.Substring(c.LastIndexOf(' ') + 1))));
        sb.Append(".ResolveAsset.g.cs");
        foreach (char invalid in "<>, ")
            sb.Replace(invalid.ToString(), "_");
        return sb.ToString();
    }

    private static string BuildSource(FieldModel type, List<FieldModel> fields)
    {
        const string core = "global::EmptyEngine.Core";
        const string objectModel = "global::EmptyEngine.ObjectModel";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        int indent = 0;
        void Line(string text = "")
        {
            if (text.Length > 0)
                sb.Append(new string(' ', indent * 4)).AppendLine(text);
            else
                sb.AppendLine();
        }

        if (type.Namespace.Length > 0)
        {
            Line($"namespace {type.Namespace}");
            Line("{");
            indent++;
        }

        bool emitHook = !type.HasOnResolveAssets && type.BaseOnResolveAssets != BaseMethod.NotOverridable;
        bool overrideHook = type.BaseOnResolveAssets
            is BaseMethod.Overridable or BaseMethod.OverridableAbstract;

        for (int i = 0; i < type.TypeChain.Length; i++)
        {
            bool innermost = i == type.TypeChain.Length - 1;
            var interfaces = new List<string>();
            if (innermost && !type.BaseHasLifecycleInterface)
                interfaces.Add($"{objectModel}.ILifecycleAttachable");
            if (innermost && !type.BaseHasHookInterface)
                interfaces.Add($"{core}.IAssetResolutionHook");
            string bases = interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : string.Empty;
            Line($"partial {type.TypeChain[i]}{bases}");
            Line("{");
            indent++;
        }

        foreach (FieldModel f in fields)
        {
            Line($"/// <summary>エディタで設定し、デシリアライズ時に <c>{f.FieldName}</c> へ解決するアセットの参照キー</summary>");
            Line($"public {core}.AssetReference<{f.FieldTypeFqn}> {f.PropertyName} {{ get; set; }}");
            Line();
        }

        Line($"/// <summary><c>[ResolveAsset]</c> フィールドの参照の解決（<c>{HookMethodName}</c> を自分で書く型はそこから呼ぶ）</summary>");
        Line($"private async global::System.Threading.Tasks.ValueTask ResolveAssetFieldsAsync({core}.IAssetResolver resolver)");
        Line("{");
        indent++;
        foreach (FieldModel f in fields)
            Line($"global::System.Threading.Tasks.ValueTask<{f.FieldTypeFqn}?> resolving{f.PropertyName} = resolver.ResolveAsync({f.PropertyName});");
        foreach (FieldModel f in fields)
            Line($"{f.FieldName} = (await resolving{f.PropertyName})!;");
        indent--;
        Line("}");

        if (emitHook)
        {
            Line();
            Line("/// <summary>フィールド値が入るたびの参照の解決</summary>");
            Line($"public {(overrideHook ? "override " : string.Empty)}async global::System.Threading.Tasks.ValueTask {HookMethodName}({core}.IAssetResolver resolver)");
            Line("{");
            indent++;
            if (type.BaseOnResolveAssets == BaseMethod.Overridable)
                Line($"await base.{HookMethodName}(resolver);");
            Line("await ResolveAssetFieldsAsync(resolver);");
            indent--;
            Line("}");
        }

        if (!type.HasOnDeserialized && type.BaseOnDeserialized is BaseMethod.None or BaseMethod.OverridableAbstract)
        {
            Line();
            Line("/// <summary>フィールド値と参照の解決が反映された後の通知</summary>");
            Line($"public {(type.BaseOnDeserialized == BaseMethod.OverridableAbstract ? "override " : string.Empty)}void OnDeserialized({objectModel}.IObject owner)");
            Line("{");
            Line("}");
        }

        if (!type.HasOnCreated && type.BaseOnCreated == BaseMethod.None)
        {
            Line();
            Line("/// <summary>オブジェクトにアタッチされたときの通知</summary>");
            Line($"public void OnCreated({objectModel}.IObject owner)");
            Line("{");
            Line("}");
        }

        if (!type.HasOnDestroy && type.BaseOnDestroy != BaseMethod.NotOverridable)
        {
            bool overrideDestroy = type.BaseOnDestroy
                is BaseMethod.Overridable or BaseMethod.OverridableAbstract;
            Line();
            Line("/// <summary>解決済みアセットへの参照を解除する</summary>");
            Line($"public {(overrideDestroy ? "override " : string.Empty)}void OnDestroy({objectModel}.IObject owner)");
            Line("{");
            indent++;
            if (type.BaseOnDestroy == BaseMethod.Overridable)
                Line("base.OnDestroy(owner);");
            foreach (FieldModel f in fields)
                Line($"{f.FieldName} = null!;");
            indent--;
            Line("}");
        }

        for (int i = 0; i < type.TypeChain.Length; i++)
        {
            indent--;
            Line("}");
        }

        if (type.Namespace.Length > 0)
        {
            indent--;
            Line("}");
        }

        return sb.ToString();
    }
}
